name: wp-post-gfm
description: 'Publish GFM Markdown files to WordPress'

branding:
  icon: 'upload-cloud'
  color: 'blue'
 
inputs:
  directory:
    required: true
  force_publish:
    description: 'Force republish all posts'
    required: false
	default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
    
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ github.action_path }}
    
    - name: Publish to WordPress
      shell: bash
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
        POSTS_DIR: ${{ inputs.directory }}
		run: node publish-to-wordpress.js
      working-directory: ${{ github.action_path }}/scripts